[package]
name = "deezer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.24", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.145"
serde_repr = "0.1.20"
thiserror = "2.0.17"

[dev-dependencies]
tokio = { version = "1.48.0", features = ["full"] }
